export const ROUTES = {
	BLOGS: {
		EDIT: '/blogs/:slug/edit',
		LIST: '/blogs',
		NEW: '/blogs/new',
		PREVIEW: '/blogs/:slug/preview',
	},
	CATEGORIES: '/categories',
	CUISINES: '/cuisines',
	DISHES: '/dishes',
	FEEDBACKS: '/feedbacks',
	GUIDELINE: '/guideline',
	HELP_CENTER: '/help-center',
	HOME: '/',
	LOGIN: '/login',
	QUOTES: '/quotes',
	RECIPES: {
		EDIT: '/recipes/:slug/edit',
		LIST: '/recipes',
		NEW: '/recipes/new',
		PREVIEW: '/recipes/:slug/preview',
	},
	REPORTS: '/reports',
	SETTINGS: '/settings',
	USERS: {
		BLACKLIST: '/users/blacklist',
		EDIT: '/users/:username/edit',
		LIST: '/users',
		NEW: '/users/new',
	},
} as const
